[project]
name = "myflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "httpx>=0.28.1",
    "pytest>=8.3.4",
]

[tool.uv.workspace]
members = ["containers/resmgr"]
